### ISSUE TITLE
"G3MWidget_iOS.h" file not found.

### ISSUE THREAD

**Issue by WuhanMonkey** [glob3mobile/g3m#112]
Hello All,

I am new to g3m so I am trying to follow the Hello World project for iOS. After following all the steps, the xcode told me that "G3MWidget_iOS.h" file not found in my ViewController.mm. But I can see it in the SDK which should be linked as library. 

This might be a simple question but I haven't figure it out. Can anyone give me some suggestions?

Also another issue I have is that, when I compile the sample Hello World project I cloned from git, the build is successful but the simulator and the real device only should a spinning white star in the app. Shouldn't it be an animated Earth?

Thank you very mcuh

**Comment by DiegoGomezDeck** [comment]
Hi @WuhanMonkey 

I think the wiki was a quiet old (I already updated it).  May be the problem is the syntax used for #import, it has to be:

``` C++
#import <G3MiOSSDK/G3MWidget_iOS.h>
#import <G3MiOSSDK/G3MBuilder_iOS.hpp>
```

Basically the pattern is:

``` C++
#import <G3MiOSSDK/AnyG3MHeader.h>
```

Related to the busy-wheel, I guess the app is having problem downloading the bitmaps for the tiles.  The intended behavior is to wait for this data (while rendering the busy wheel) before rendering the planet.  Please check the application log looking for download errors.

**Comment by WuhanMonkey** [comment]
Thank you very much @DiegoGomezDeck, it is very helpful.
