### ISSUE TITLE
Marks not display - depending on camera pitch?

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#18]
I placed a number of marks into a MarksRenderer, with specifying minDistanceToCamera as 0. interestingly some marks are not displayed, depending on camera attitude?

please see to screenshots attached, which are of the very same app, a few seconds apart. on one, the Marks are there, on the other, they are not

I wonder what the cause of this issue is, and how to solve

(can provide source code if needed)

![device-2013-12-13-134043](https://f.cloud.github.com/assets/333140/1742132/25332ba8-63f4-11e3-89dc-2a54ef9ca911.png)
![device-2013-12-13-134031](https://f.cloud.github.com/assets/333140/1742133/2546eb70-63f4-11e3-9ff0-681d2a269ea8.png)

**Comment by DiegoGomezDeck** [comment]
This is a confirmed bug.  I'll let this issue open for fixing it soon.

**Comment by amazingsmash** [comment]
The bug was a confirmed flaw of our's marks horizon culling when the mark was situated above camera height. I've just pushed a fix in purgatory which should solve this issue allowing the user to display such marks.

![device-2013-12-16-162606](https://f.cloud.github.com/assets/1220012/1756094/f23eaee8-666e-11e3-92fd-9e9b23aba489.png)
