### ISSUE TITLE
some functionality is lost with the new renderer

### ISSUE THREAD

**Issue by akosmaroy** [glob3mobile/g3m#76]
I've merge the new purgatory code, which now includes the renderer refactorying, into our applications codebase, and I've found that some functionality is lost.

namely, we've seem to have lost:
- G3MWidget.setCameraHeadingPitchRoll()
- G3MWidget.setCurrentCamera()
- G3MWidget.getPlanetRenderer().setRenderTileMeshes()
- Camera.setGeodeticPositionStablePitch()
- Camera().getHeadingPitchRoll()
- the TaitBryanAngles type is gone
- ShapeRenderer.removeShape()
- Color.Color.fromRGBA255()
- Later.setTitle()
- PlanetRenderer.setQuality()
- the type DefaultRenderer

please provide ways of achieving the same functionality as above with the new API

I also see that the 'absolute' / 'realtive' altitude mode is gone now - can you confirm that now all elevation is treated as 'absolute'?

**Comment by DiegoGomezDeck** [comment]
Hi @akosmaroy 

I just checked, and most (if not all) methods are in purgatory branch. May be you have some garbage on your local copy?

> I also see that the 'absolute' / 'realtive' altitude mode is gone now - can you confirm that now all elevation is treated as 'absolute'?

The only change there is that I removed the Shape::setPosittion(Geodetic3D, AltitudeMode) method.... the change of the AltitudeMode was not working, so I removed this method and the AltitudeMode is fixed on the contruction time.  Take note that Shape::setPosittion(Geodetic3D) method is still there.  In short: you still can change the position, but the AltitudeMode is fixed after you create the shape.

**Comment by akosmaroy** [comment]
indeed, my mistake. my submodule-based git magic got all !@#!@d up

the only thing I see missing now is:
- G3MRenderContext.getFactory().deleteImage()
- e.g. IFactory.deleteImage()

I wonder if this is intentional

**Comment by DiegoGomezDeck** [comment]
@akosmaroy 

Yes, it's intentional... The idea is to avoid some virtual-calls in Android.

Just replace your "old" code with:

 G3MRenderContext.getFactory().deleteImage( theImage );  // note there are 2 virtual-method calls here that can be completely avoid just calling IImage::dispose()

to something like that:

 if ( theImage != NULL) {
   theImage.dispose();  // mandatory, this releases expensive Bitmap memory
   theImage = null;  // optional, based on your case.  it's just intended to release memory asap.
 }
